name: 'Simple Version Bumper'
description: 'Bump version numbers in project files'
inputs:
  config:
    description: 'Path to config YAML file (overrides other inputs if provided)'
    required: false
  files:
    description: 'Comma-separated list of files to update version in (ignored if config is provided)'
    required: false
  bump_type:
    description: 'Type of version bump (major/minor/patch/git) (ignored if config is provided)'
    required: false
    default: 'patch'
  force:
    description: 'Force version change when current version is a git tag or when switching to git tag from semantic version'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install simplebumpversion
      shell: bash
      run: pip install simplebumpversion

    - name: Bump version with config
      if: inputs.config != ''
      shell: bash
      run: bump-version --config ${{ inputs.config }}

    - name: Bump version with direct inputs
      if: inputs.config == ''
      shell: bash
      run: |
        FILES="${{ inputs.files }}"
        # Convert comma-separated list to space-separated for the CLI
        FILES="${FILES//,/ }"

        # Handle force flag
        FORCE_FLAG=""
        if [[ "${{ inputs.force }}" == "true" ]]; then
          FORCE_FLAG="--force"
        fi

        # Handle bump type
        if [[ "${{ inputs.bump_type }}" == "major" ]]; then
          bump-version $FILES --major $FORCE_FLAG
        elif [[ "${{ inputs.bump_type }}" == "minor" ]]; then
          bump-version $FILES --minor $FORCE_FLAG
        elif [[ "${{ inputs.bump_type }}" == "patch" ]]; then
          bump-version $FILES --patch $FORCE_FLAG
        elif [[ "${{ inputs.bump_type }}" == "git" ]]; then
          bump-version $FILES --git $FORCE_FLAG
        else
          # Default to patch
          bump-version $FILES --patch $FORCE_FLAG
        fi

branding:
  icon: 'arrow-up'
  color: 'blue'
