name: 'Simple Version Bumper'
description: 'Bump version numbers in project files'
inputs:
  file:
    description: 'Path to the file containing the version number'
    required: false
  bump_type:
    description: 'Type of version bump (minor, patch, git)'
    required: false
    default: 'patch'
  config:
    description: 'Yaml file with configurations'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - '--${{ inputs.bump_type }}'
    - ${{ inputs.config }}
branding:
  icon: 'arrow-up'
  color: 'blue'
