name: 'Patch bump' # Configuration name
description: 'Bump the patch version' # description

settings:
  bump_type: patch
  files: # list of files to update
    - pyproject.toml
  force: false # Set to true to force version change when current version is a git tag
