name: Bump Version

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type (major/minor/patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write

jobs:
  bump-version:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump type from PR labels
        id: bump_type
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "type=${{ inputs.bump_type }}" >> $GITHUB_OUTPUT
          else
            if [ "${{ contains(github.event.pull_request.labels.*.name, 'major') }}" == "true" ]; then
              echo "type=major" >> $GITHUB_OUTPUT
            elif [ "${{ contains(github.event.pull_request.labels.*.name, 'minor') }}" == "true" ]; then
              echo "type=minor" >> $GITHUB_OUTPUT
            else
              echo "type=patch" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Bump version
        uses: Ikromov247/bump_version@v2.0.2
        with:
          config: 'bump_config.yml'

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Bump version [skip ci]"
          git push
